DNA_sequence0 = input("Enter your DNA sequence here: \n")
DNA = DNA_sequence0.upper()
DNA_to_CODONs = ([DNA[start:start+3]for start in range(0,len(DNA),3)])

for i in DNA_to_CODONs:
  if (i=="ATG"): print("MET",end = ' ')
  if (i=="TGA" or i=="TAA" or i=="TAG"): print("STOP",end = ' ')
  if (i=="GCT" or i=="GCC" or i=="GCA" or i=="GCG"): print("ALA",end = ' ')
  if (i=="CGT" or i=="CGC" or i=="CGA" or i=="CGG" or i=="AGA" or i=="AGG"): print("ARG",end = ' ')
  if (i=="AAT" or i=="AAC"): print("ASN",end = ' ')
  if (i=="GAT" or i=="GAC"): print("ASP",end = ' ')
  if (i=="TGT" or i=="TGC"): print("CYS",end = ' ')
  if (i=="CAA" or i=="CAG"): print("GLN",end = ' ')
  if (i=="GAA" or i=="GAG"): print("GLU",end = ' ')
  if (i=="GGT" or i=="GGC" or i=="GGA" or i=="GGG"): print("GLY",end = ' ')
  if (i=="CAT" or i=="CAC"): print("HIS",end = ' ')
  if (i=="ATT" or i=="ATC" or i=="ATA"): print("ILE",end = ' ')
  if (i=="CTT" or i=="CTC" or i=="CTA" or i=="CTG" or i=="TTA" or i=="TTG"): print("LEU",end = ' ')
  if (i=="AAA" or i=="AAG"): print("LYS",end = ' ')
  if (i=="TTT" or i=="TTC"): print("PHE",end = ' ')
  if (i=="CCT" or i=="CCC" or i=="CCA" or i=="CCG"): print("PRO",end = ' ')
  if (i=="TCT" or i=="TCC" or i=="TCA" or i=="TCG" or i=="AGT" or i=="AGC"): print("SER",end = ' ')
  if (i=="ACT" or i=="ACC" or i=="ACA" or i=="ACG"): print("THR",end = ' ')
  if (i=="TGG"): print("TRP",end = ' ')
  if (i=="TAT" or i=="TAC"): print("TYR",end = ' ')
  if (i=="GTT" or i=="GTC" or i=="GTA" or i=="GTG"): print("VAL",end = ' ')